
        package com.unsa.ui;

        import com.intellij.uiDesigner.core.GridConstraints;
        import com.intellij.uiDesigner.core.GridLayoutManager;
        import com.unsa.logic.Utils;

        import java.awt.event.ActionListener;
        import javax.swing.*;
        import java.awt.event.ActionEvent;
        import java.awt.*;

        public class Panel {
            private static final int DEFAULT_WITH = 800;
            private static final int DEFAULT_HEIGHT = 600;
            private JTabbedPane zoom;
            public JPanel panel1;
            private JComboBox comboBox1;
            private JPanel image11;
            private JPanel image12;
            private JPanel image13;
            private JTextField textField11;
            private JPanel image21;
            private JPanel image22;
            private JButton button21;
            private JTextPane textPane21;
            private JButton jButtonMedia;
            private JPanel image31;
            private JPanel image32;
            private JTextField textFieldMediana;
            private JPanel image41;
            private JPanel image42;
            private JButton MOSTRARButton;
            private JTextField zoomTextValue;

            private void createUIComponents() {
                // TODO: place custom component creation code here
                image11 = new ImageSelector(true, 1);
                image11.setMinimumSize(new Dimension(DEFAULT_WITH / 2, DEFAULT_HEIGHT / 2));
                image12 = new ImageSelector(false, 2);
                image12.setMinimumSize(new Dimension(DEFAULT_WITH / 2, DEFAULT_HEIGHT / 2));
                image13 = new ImageSelector(false, 3);
                image13.setMinimumSize(new Dimension(DEFAULT_WITH / 2, DEFAULT_HEIGHT / 2));

                // Convolucional
                image21 = new ImageSelector(true, 4);
                image21.setMinimumSize(new Dimension(DEFAULT_WITH / 2, DEFAULT_HEIGHT / 2));
                image22 = new ImageSelector(false, 5);
                image22.setMinimumSize(new Dimension(DEFAULT_WITH / 2, DEFAULT_HEIGHT / 2));
                textPane21 = new JTextPane();
                textPane21.setText("0.1;0.1;0.1\n" +
                        "0.1;0.1;0.1\n" +
                        "0.1;0.1;0.1");
                Utils.setPane(textPane21);


                image31 = new ImageSelector(true, 4);
                image31.setMinimumSize(new Dimension(DEFAULT_WITH / 2, DEFAULT_HEIGHT / 2));
                image32 = new ImageSelector(false, 5);
                image32.setMinimumSize(new Dimension(DEFAULT_WITH / 2, DEFAULT_HEIGHT / 2));


                image41 = new ImageSelector(true, 4);
                image41.setMinimumSize(new Dimension(DEFAULT_WITH / 2, DEFAULT_HEIGHT / 2));
                image42 = new ImageSelector(false, 5);
                image42.setMinimumSize(new Dimension(DEFAULT_WITH / 2, DEFAULT_HEIGHT / 2));

            }

            public static void main(String[] args) {
                JFrame frame = new JFrame("Panel");
                //frame.setIconImage();
                Panel mainPanel = new Panel();
                mainPanel.updateButton();
                frame.setContentPane(mainPanel.panel1);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();

                frame.setVisible(true);
                frame.setMinimumSize(new Dimension(DEFAULT_WITH, DEFAULT_HEIGHT));
            }

            private void updateButton() {

            }

            {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
                $$$setupUI$$$();
            }

            /**
             * Method generated by IntelliJ IDEA GUI Designer
             * >>> IMPORTANT!! <<<
             * DO NOT edit this method OR call it in your code!
             *
             * @noinspection ALL
             */
            private void $$$setupUI$$$() {
                createUIComponents();
                panel1 = new JPanel();
                panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
                zoom = new JTabbedPane();
                panel1.add(zoom, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
                final JPanel panel2 = new JPanel();
                panel2.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
                zoom.addTab("Transformada de Fourier", panel2);
                panel2.add(image11, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
                panel2.add(image12, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
                final JPanel panel3 = new JPanel();
                panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
                panel2.add(panel3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
                final JLabel label1 = new JLabel();
                label1.setText("Transformada de Fourier");
                panel3.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
                panel2.add(image13, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
                final JPanel panel4 = new JPanel();
                panel4.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
                zoom.addTab("Convolucional", panel4);
                panel4.add(image21, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
                panel4.add(image22, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
                final JPanel panel5 = new JPanel();
                panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
                panel4.add(panel5, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
                final JLabel label2 = new JLabel();
                label2.setText("Agregar el kernel separado por ; y \\n");
                panel5.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
                final JPanel panel6 = new JPanel();
                panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
                panel4.add(panel6, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
                panel6.add(textPane21, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
            }

            /**
             * @noinspection ALL
             */
            public JComponent $$$getRootComponent$$$() {
                return panel1;
            }

        }




